import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { formatIdrDecimal, sumIdrDecimals } from "@/lib/money";
import { FileDown, FileText } from "lucide-react";
import { useMemo, useState } from "react";

function dateInput(date: Date) { return date.toISOString().slice(0, 10); }

export default function Reports() {
  const { user } = useAuth();
  const [from, setFrom] = useState(() => dateInput(new Date(new Date().getFullYear(), new Date().getMonth(), 1)));
  const [to, setTo] = useState(() => dateInput(new Date(Date.now() + 86_400_000)));
  const params = useMemo(() => ({ from: new Date(`${from}T00:00:00`), to: new Date(`${to}T00:00:00`) }), [from, to]);
  const { data, isLoading } = trpc.reports.transactions.useQuery(params, { enabled: Boolean(user) });
  const { data: recap, isLoading: recapLoading } = trpc.reports.transactionRecap.useQuery(params, { enabled: Boolean(user) });
  const { data: stockRows } = trpc.reports.stockOpnames.useQuery(params, { enabled: Boolean(user) });
  const { data: historicalRows, isLoading: historicalLoading } = trpc.reports.historicalTransactions.useQuery(params, { enabled: Boolean(user) });
  const total = sumIdrDecimals(data?.filter(({ transaction }) => transaction.status !== "CANCELLED").map(({ transaction }) => String(transaction.rupiahAmount)) ?? []);
  const historicalTotal = sumIdrDecimals(historicalRows?.map(({ transaction }) => String(transaction.rupiahAmount)) ?? []);

  const setPresetToday = () => { setFrom(dateInput(new Date())); setTo(dateInput(new Date(Date.now() + 86_400_000))); };
  const setPresetThisMonth = () => { setFrom(dateInput(new Date(new Date().getFullYear(), new Date().getMonth(), 1))); setTo(dateInput(new Date(Date.now() + 86_400_000))); };

  return <div className="mx-auto max-w-7xl space-y-6 print-report">
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold tracking-[0.16em] text-[#5c8f53] uppercase"><FileText className="size-4" /> Pelaporan</div><h1 className="font-display text-3xl font-semibold tracking-tight text-[#18395f]">Laporan transaksi</h1><p className="mt-2 text-sm text-[#475569]">Pilih rentang harian atau bulanan, lalu ekspor arsip dengan data dan periode yang terlihat.</p></div><div className="no-print text-left sm:text-right"><Button onClick={() => window.print()} className="bg-[#183f70] text-white hover:bg-[#12345d]"><FileDown className="mr-2 size-4" /> Ekspor PDF / cetak</Button><p className="mt-2 text-xs text-[#475569]">Pada dialog perangkat, pilih <strong>Simpan sebagai PDF</strong> untuk arsip digital atau printer untuk arsip fisik.</p></div></section>
    <Card className="no-print border-[#dce6f0]"><CardContent className="space-y-4 py-5">
      <div className="flex flex-wrap gap-2"><Button type="button" size="sm" variant="outline" onClick={setPresetToday}>Hari ini</Button><Button type="button" size="sm" variant="outline" onClick={setPresetThisMonth}>Bulan ini</Button></div>
      <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-1.5"><Label>Tanggal mulai</Label><Input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></div><div className="space-y-1.5"><Label>Tanggal akhir eksklusif</Label><Input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></div></div>
    </CardContent></Card>

    <Card className="border-[#dce6f0]">
      <CardHeader><CardTitle className="font-display text-xl text-[#18395f]">Rekap keuangan transaksi</CardTitle><CardDescription>Hanya transaksi berstatus <strong>Selesai</strong> (sudah terposting ke kas/stok) dalam periode terpilih. Estimasi margin kotor memakai metode rata-rata tertimbang (kurs jual rata-rata dikurangi kurs beli rata-rata pada volume yang cocok) — ini <strong>bukan</strong> perhitungan laba akuntansi penuh berbasis FIFO, gunakan sebagai indikasi kasar saja.</CardDescription></CardHeader>
      <CardContent>
        {recapLoading ? <p className="text-sm text-[#475569]">Memuat rekap…</p> : null}
        {!recapLoading && recap ? <>
          <div className="grid gap-3 sm:grid-cols-4">
            <RecapMetric label="Transaksi selesai" value={String(recap.transactionCount)} />
            <RecapMetric label="Turnover total" value={formatIdrDecimal(recap.totalTurnoverRupiah)} />
            <RecapMetric label="Total beli (Rp)" value={formatIdrDecimal(recap.totalBuyRupiah)} sub={`${recap.buyCount} bon`} />
            <RecapMetric label="Total jual (Rp)" value={formatIdrDecimal(recap.totalSellRupiah)} sub={`${recap.sellCount} bon`} />
          </div>
          <div className="mt-4 rounded-xl bg-[#f7fbf6] border border-emerald-100 px-4 py-3"><p className="text-xs font-bold uppercase tracking-wide text-emerald-800">Estimasi margin kotor periode ini</p><p className="mt-1 font-display text-2xl text-emerald-900">{formatIdrDecimal(recap.totalGrossMarginEstimate)}</p></div>
          <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-[#dce6f0] text-xs tracking-wide text-[#475569] uppercase"><tr><th className="px-3 py-2">Valuta</th><th className="px-3 py-2">Beli (volume/Rp/kurs rata²)</th><th className="px-3 py-2">Jual (volume/Rp/kurs rata²)</th><th className="px-3 py-2">Estimasi margin</th></tr></thead><tbody>{recap.currencies.length ? recap.currencies.map((row) => <tr key={row.currencyCode} className="border-b border-[#edf2f6]"><td className="px-3 py-2 font-medium text-[#18395f]">{row.currencyCode}</td><td className="px-3 py-2 table-number">{row.buyCount ? `${row.buyForeignTotal} · ${formatIdrDecimal(row.buyRupiahTotal)} · @${row.avgBuyRate}` : "—"}</td><td className="px-3 py-2 table-number">{row.sellCount ? `${row.sellForeignTotal} · ${formatIdrDecimal(row.sellRupiahTotal)} · @${row.avgSellRate}` : "—"}</td><td className="px-3 py-2 table-number font-semibold">{row.grossMarginEstimate ? formatIdrDecimal(row.grossMarginEstimate) : "—"}</td></tr>) : <tr><td colSpan={4} className="px-3 py-6 text-center text-[#475569]">Tidak ada transaksi selesai pada periode ini.</td></tr>}</tbody></table></div>
        </> : null}
      </CardContent>
    </Card>

    <Card className="border-[#dce6f0]"><CardHeader><CardTitle className="font-display text-xl text-[#18395f]">PT IBU KOTA VALASINDO — Rekap transaksi</CardTitle><CardDescription>Periode {from} s.d. {to} · {data?.length ?? 0} baris · total non-batal <span className="table-number font-semibold text-[#18395f]">{total}</span></CardDescription></CardHeader><CardContent><p className="mb-4 hidden text-xs text-[#475569] print:block">Arsip laporan · diekspor {new Date().toLocaleString("id-ID")}</p><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-[#dce6f0] text-xs tracking-wide text-[#475569] uppercase"><tr><th className="px-3 py-3">Waktu</th><th className="px-3 py-3">Nomor</th><th className="px-3 py-3">Nasabah</th><th className="px-3 py-3">Jenis</th><th className="px-3 py-3">Valuta</th><th className="px-3 py-3">Kurs snapshot</th><th className="px-3 py-3">Rupiah</th><th className="px-3 py-3">Status</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={8} className="px-3 py-8 text-center text-[#475569]">Memuat laporan…</td></tr> : data?.length ? data.map(({ transaction, customer, currency }) => <tr key={transaction.id} className="border-b border-[#edf2f6]"><td className="px-3 py-3 text-xs text-[#475569]">{new Date(transaction.transactionAt).toLocaleString("id-ID")}</td><td className="px-3 py-3 font-medium text-[#18395f]">{transaction.transactionNumber}</td><td className="px-3 py-3">{customer.fullName}</td><td className="px-3 py-3">{transaction.operation}</td><td className="px-3 py-3 table-number">{String(transaction.foreignAmount)} {currency.code}</td><td className="px-3 py-3 table-number">{String(transaction.rateSnapshot)}</td><td className="px-3 py-3 table-number font-semibold">{String(transaction.rupiahAmount)}</td><td className="px-3 py-3"><Badge className={{ DRAFT: "status-pending", PENDING_REVIEW: "status-pending", APPROVED: "status-approved", COMPLETED: "status-approved", RETURNED: "status-rejected", CANCELLED: "status-rejected" }[transaction.status] ?? "status-inactive"}>{transaction.status}</Badge></td></tr>) : <tr><td colSpan={8} className="px-3 py-8 text-center text-[#475569]">Tidak ada transaksi dalam periode tersebut.</td></tr>}</tbody></table></div></CardContent></Card>
    <Card className="border-[#dce6f0]"><CardHeader><CardTitle className="font-display text-xl text-[#18395f]">Stock opname</CardTitle><CardDescription>Rekap saldo sistem, fisik, variance, dan status rekonsiliasi untuk periode laporan yang dipilih.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b border-[#dce6f0] text-xs tracking-wide text-[#475569] uppercase"><tr><th className="px-3 py-3">Tanggal</th><th className="px-3 py-3">Valuta</th><th className="px-3 py-3">Sistem</th><th className="px-3 py-3">Fisik</th><th className="px-3 py-3">Variance</th><th className="px-3 py-3">Status</th></tr></thead><tbody>{stockRows?.length ? stockRows.map(({ opname, currency }) => <tr key={opname.id} className="border-b border-[#edf2f6]"><td className="px-3 py-3">{new Date(opname.opnameDate).toLocaleDateString("id-ID")}</td><td className="px-3 py-3 font-medium text-[#18395f]">{currency.code}</td><td className="px-3 py-3 table-number">{String(opname.closingSystemBalance)}</td><td className="px-3 py-3 table-number">{opname.physicalBalance === null ? "—" : String(opname.physicalBalance)}</td><td className={`px-3 py-3 table-number ${opname.variance !== null && Number(opname.variance) !== 0 ? "font-semibold text-rose-700" : ""}`}>{opname.variance === null ? "—" : String(opname.variance)}</td><td className="px-3 py-3"><Badge className={opname.reconciliationStatus === "VARIANCE" ? "status-rejected" : opname.reconciliationStatus === "RECONCILED" ? "status-approved" : "status-pending"}>{opname.reconciliationStatus}</Badge></td></tr>) : <tr><td colSpan={6} className="px-3 py-8 text-center text-[#475569]">Belum ada stock opname dalam periode ini.</td></tr>}</tbody></table></div></CardContent></Card>
    <Card className="border-amber-200 bg-amber-50/40"><CardHeader><CardTitle className="font-display text-xl text-[#18395f]">Arsip transaksi historis</CardTitle><CardDescription>Catatan ledger impor untuk verifikasi dan rekonsiliasi. Data ini tidak digunakan dalam kurs aktif, KYC live, saldo kas, antrean review, atau rekap transaksi operasional.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-amber-200 text-xs tracking-wide text-[#475569] uppercase"><tr><th className="px-3 py-3">Tanggal</th><th className="px-3 py-3">Nomor arsip</th><th className="px-3 py-3">Nasabah sumber</th><th className="px-3 py-3">Jenis</th><th className="px-3 py-3">Valuta</th><th className="px-3 py-3">Kurs</th><th className="px-3 py-3">Rupiah</th></tr></thead><tbody>{historicalLoading ? <tr><td colSpan={7} className="px-3 py-8 text-center text-[#475569]">Memuat arsip historis…</td></tr> : historicalRows?.length ? historicalRows.map(({ transaction, customer, currency }) => <tr key={transaction.id} className="border-b border-amber-100"><td className="px-3 py-3 text-xs text-[#475569]">{new Date(transaction.transactionAt).toLocaleDateString("id-ID")}</td><td className="px-3 py-3 font-medium text-[#18395f]">{transaction.transactionNumber}</td><td className="px-3 py-3">{customer.fullName}</td><td className="px-3 py-3">{transaction.operation}</td><td className="px-3 py-3 table-number">{String(transaction.foreignAmount)} {currency.code}</td><td className="px-3 py-3 table-number">{String(transaction.rateSnapshot)}</td><td className="px-3 py-3 table-number font-semibold">{String(transaction.rupiahAmount)}</td></tr>) : <tr><td colSpan={7} className="px-3 py-8 text-center text-[#475569]">Tidak ada arsip historis pada periode ini.</td></tr>}</tbody></table></div><p className="mt-3 text-sm font-semibold text-amber-800">Total arsip dalam periode: <span className="table-number">{historicalTotal}</span></p></CardContent></Card>
  </div>;
}

function RecapMetric({ label, value, sub }: { label: string; value: string; sub?: string }) {
  return <div className="rounded-xl bg-[#f7f9fc] px-3 py-3"><p className="text-[11px] font-bold uppercase tracking-wide text-[#8190a4]">{label}</p><p className="mt-1 table-number text-lg font-semibold text-[#18395f]">{value}</p>{sub ? <p className="mt-0.5 text-xs text-[#8190a4]">{sub}</p> : null}</div>;
}
