import { useAuth } from "@/_core/hooks/useAuth";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { sumIdrDecimals } from "@/lib/money";
import { FileDown, FileText } from "lucide-react";
import { useMemo, useState } from "react";

function dateInput(date: Date) { return date.toISOString().slice(0, 10); }

export default function Reports() {
  const { user } = useAuth();
  const [from, setFrom] = useState(() => dateInput(new Date(new Date().getFullYear(), new Date().getMonth(), 1)));
  const [to, setTo] = useState(() => dateInput(new Date(Date.now() + 86_400_000)));
  const params = useMemo(() => ({ from: new Date(`${from}T00:00:00`), to: new Date(`${to}T00:00:00`) }), [from, to]);
  const { data, isLoading } = trpc.reports.transactions.useQuery(params, { enabled: Boolean(user) });
  const { data: stockRows } = trpc.reports.stockOpnames.useQuery(params, { enabled: Boolean(user) });
  const { data: historicalRows, isLoading: historicalLoading } = trpc.reports.historicalTransactions.useQuery(params, { enabled: Boolean(user) });
  const total = sumIdrDecimals(data?.filter(({ transaction }) => transaction.status !== "CANCELLED").map(({ transaction }) => String(transaction.rupiahAmount)) ?? []);
  const historicalTotal = sumIdrDecimals(historicalRows?.map(({ transaction }) => String(transaction.rupiahAmount)) ?? []);

  return <div className="mx-auto max-w-7xl space-y-6 print-report">
    <section className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold tracking-[0.16em] text-[#5c8f53] uppercase"><FileText className="size-4" /> Pelaporan</div><h1 className="font-display text-3xl font-semibold tracking-tight text-[#18395f]">Laporan transaksi</h1><p className="mt-2 text-sm text-[#64748b]">Pilih rentang harian atau bulanan, lalu ekspor arsip dengan data dan periode yang terlihat.</p></div><div className="no-print text-left sm:text-right"><Button onClick={() => window.print()} className="bg-[#183f70] text-white hover:bg-[#12345d]"><FileDown className="mr-2 size-4" /> Ekspor PDF / cetak</Button><p className="mt-2 text-xs text-[#64748b]">Pada dialog perangkat, pilih <strong>Simpan sebagai PDF</strong> untuk arsip digital atau printer untuk arsip fisik.</p></div></section>
    <Card className="no-print border-[#dce6f0]"><CardContent className="grid gap-4 py-5 sm:grid-cols-2"><div className="space-y-1.5"><Label>Tanggal mulai</Label><Input type="date" value={from} onChange={(event) => setFrom(event.target.value)} /></div><div className="space-y-1.5"><Label>Tanggal akhir eksklusif</Label><Input type="date" value={to} onChange={(event) => setTo(event.target.value)} /></div></CardContent></Card>
    <Card className="border-[#dce6f0]"><CardHeader><CardTitle className="font-display text-xl text-[#18395f]">PT IBU KOTA VALASINDO — Rekap transaksi</CardTitle><CardDescription>Periode {from} s.d. {to} · {data?.length ?? 0} baris · total non-batal <span className="table-number font-semibold text-[#18395f]">{total}</span></CardDescription></CardHeader><CardContent><p className="mb-4 hidden text-xs text-[#64748b] print:block">Arsip laporan · diekspor {new Date().toLocaleString("id-ID")}</p><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-[#dce6f0] text-xs tracking-wide text-[#64748b] uppercase"><tr><th className="px-3 py-3">Waktu</th><th className="px-3 py-3">Nomor</th><th className="px-3 py-3">Nasabah</th><th className="px-3 py-3">Jenis</th><th className="px-3 py-3">Valuta</th><th className="px-3 py-3">Kurs snapshot</th><th className="px-3 py-3">Rupiah</th><th className="px-3 py-3">Status</th></tr></thead><tbody>{isLoading ? <tr><td colSpan={8} className="px-3 py-8 text-center text-[#64748b]">Memuat laporan…</td></tr> : data?.length ? data.map(({ transaction, customer, currency }) => <tr key={transaction.id} className="border-b border-[#edf2f6]"><td className="px-3 py-3 text-xs text-[#64748b]">{new Date(transaction.transactionAt).toLocaleString("id-ID")}</td><td className="px-3 py-3 font-medium text-[#18395f]">{transaction.transactionNumber}</td><td className="px-3 py-3">{customer.fullName}</td><td className="px-3 py-3">{transaction.operation}</td><td className="px-3 py-3 table-number">{String(transaction.foreignAmount)} {currency.code}</td><td className="px-3 py-3 table-number">{String(transaction.rateSnapshot)}</td><td className="px-3 py-3 table-number font-semibold">{String(transaction.rupiahAmount)}</td><td className="px-3 py-3"><Badge className={{ DRAFT: "status-pending", PENDING_REVIEW: "status-pending", APPROVED: "status-approved", COMPLETED: "status-approved", RETURNED: "status-rejected", CANCELLED: "status-rejected" }[transaction.status] ?? "status-inactive"}>{transaction.status}</Badge></td></tr>) : <tr><td colSpan={8} className="px-3 py-8 text-center text-[#64748b]">Tidak ada transaksi dalam periode tersebut.</td></tr>}</tbody></table></div></CardContent></Card>
    <Card className="border-[#dce6f0]"><CardHeader><CardTitle className="font-display text-xl text-[#18395f]">Stock opname</CardTitle><CardDescription>Rekap saldo sistem, fisik, variance, dan status rekonsiliasi untuk periode laporan yang dipilih.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b border-[#dce6f0] text-xs tracking-wide text-[#64748b] uppercase"><tr><th className="px-3 py-3">Tanggal</th><th className="px-3 py-3">Valuta</th><th className="px-3 py-3">Sistem</th><th className="px-3 py-3">Fisik</th><th className="px-3 py-3">Variance</th><th className="px-3 py-3">Status</th></tr></thead><tbody>{stockRows?.length ? stockRows.map(({ opname, currency }) => <tr key={opname.id} className="border-b border-[#edf2f6]"><td className="px-3 py-3">{new Date(opname.opnameDate).toLocaleDateString("id-ID")}</td><td className="px-3 py-3 font-medium text-[#18395f]">{currency.code}</td><td className="px-3 py-3 table-number">{String(opname.closingSystemBalance)}</td><td className="px-3 py-3 table-number">{opname.physicalBalance === null ? "—" : String(opname.physicalBalance)}</td><td className={`px-3 py-3 table-number ${opname.variance !== null && Number(opname.variance) !== 0 ? "font-semibold text-rose-700" : ""}`}>{opname.variance === null ? "—" : String(opname.variance)}</td><td className="px-3 py-3"><Badge className={opname.reconciliationStatus === "VARIANCE" ? "status-rejected" : opname.reconciliationStatus === "RECONCILED" ? "status-approved" : "status-pending"}>{opname.reconciliationStatus}</Badge></td></tr>) : <tr><td colSpan={6} className="px-3 py-8 text-center text-[#64748b]">Belum ada stock opname dalam periode ini.</td></tr>}</tbody></table></div></CardContent></Card>
    <Card className="border-amber-200 bg-amber-50/40"><CardHeader><CardTitle className="font-display text-xl text-[#18395f]">Arsip transaksi historis</CardTitle><CardDescription>Catatan ledger impor untuk verifikasi dan rekonsiliasi. Data ini tidak digunakan dalam kurs aktif, KYC live, saldo kas, antrean review, atau rekap transaksi operasional.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="border-b border-amber-200 text-xs tracking-wide text-[#64748b] uppercase"><tr><th className="px-3 py-3">Tanggal</th><th className="px-3 py-3">Nomor arsip</th><th className="px-3 py-3">Nasabah sumber</th><th className="px-3 py-3">Jenis</th><th className="px-3 py-3">Valuta</th><th className="px-3 py-3">Kurs</th><th className="px-3 py-3">Rupiah</th></tr></thead><tbody>{historicalLoading ? <tr><td colSpan={7} className="px-3 py-8 text-center text-[#64748b]">Memuat arsip historis…</td></tr> : historicalRows?.length ? historicalRows.map(({ transaction, customer, currency }) => <tr key={transaction.id} className="border-b border-amber-100"><td className="px-3 py-3 text-xs text-[#64748b]">{new Date(transaction.transactionAt).toLocaleDateString("id-ID")}</td><td className="px-3 py-3 font-medium text-[#18395f]">{transaction.transactionNumber}</td><td className="px-3 py-3">{customer.fullName}</td><td className="px-3 py-3">{transaction.operation}</td><td className="px-3 py-3 table-number">{String(transaction.foreignAmount)} {currency.code}</td><td className="px-3 py-3 table-number">{String(transaction.rateSnapshot)}</td><td className="px-3 py-3 table-number font-semibold">{String(transaction.rupiahAmount)}</td></tr>) : <tr><td colSpan={7} className="px-3 py-8 text-center text-[#64748b]">Tidak ada arsip historis pada periode ini.</td></tr>}</tbody></table></div><p className="mt-3 text-sm font-semibold text-amber-800">Total arsip dalam periode: <span className="table-number">{historicalTotal}</span></p></CardContent></Card>
  </div>;
}
