import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { formatIdrDecimal } from "@/lib/money";
import { trpc } from "@/lib/trpc";
import { Calculator, FileText, Printer, ShieldAlert, ShieldCheck } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";

function printTrainingResult(title: string, rows: Array<[string, string]>) {
  const body = rows.map(([label, value]) => `<tr><td>${label}</td><td>${value}</td></tr>`).join("");
  const popup = window.open("", "_blank");
  if (!popup) return toast.error("Izinkan pop-up browser untuk mencetak hasil latihan.");
  popup.document.write(`<!doctype html><title>${title}</title><style>body{font-family:Arial;margin:32px;color:#18395f}h1{font-size:22px}table{border-collapse:collapse;width:100%;margin-top:18px}td{border:1px solid #94a7b8;padding:9px}.notice{margin-top:18px;border:2px solid #a35c00;padding:12px;color:#805000;font-weight:bold}</style><h1>${title}</h1><p>PT Ibukota Valasindo · ${new Date().toLocaleString("id-ID")}</p><table>${body}</table><p class=notice>SIMULASI — TIDAK MASUK LAPORAN, SALDO KAS, ATAU NOMOR BON RESMI.</p><script>window.print()</script>`);
  popup.document.close();
}

function Field({ label, value, setValue }: { label: string; value: string; setValue: (value: string) => void }) {
  return <div><Label>{label}</Label><Input className="mt-2" inputMode="decimal" value={value} onChange={(event) => setValue(event.target.value)} /></div>;
}

function Result({ title, main, rows }: { title: string; main: string; rows: Array<[string, string]> }) {
  return <div className="mt-5 rounded-xl bg-[#f5f8fc] p-4"><p className="text-xs font-bold tracking-wide text-[#475569] uppercase">{title}</p><p className="table-number mt-2 text-xl font-semibold text-[#18395f]">{main}</p><Button size="sm" variant="outline" className="mt-3" onClick={() => printTrainingResult(title, rows)}><Printer className="mr-1.5 size-3.5" />Simpan PDF / cetak latihan</Button></div>;
}

export default function SafeSimulation() {
  const [foreignAmount, setForeignAmount] = useState("100"); const [rate, setRate] = useState("17700"); const [quoteUnit, setQuoteUnit] = useState("1");
  const [systemBalance, setSystemBalance] = useState("500"); const [physicalBalance, setPhysicalBalance] = useState("500");
  const [referenceRate, setReferenceRate] = useState("17700"); const [proposedRate, setProposedRate] = useState("18100"); const [reviewThresholdPercent, setReviewThresholdPercent] = useState("2");
  const [closingChecklistComplete, setClosingChecklistComplete] = useState(true); const [stockOpnameReconciled, setStockOpnameReconciled] = useState(true);
  const exchange = trpc.simulation.exchange.useMutation({ onError: (error) => toast.error(error.message) });
  const closing = trpc.simulation.closing.useMutation({ onError: (error) => toast.error(error.message) });
  const rateShock = trpc.simulation.rateShock.useMutation({ onError: (error) => toast.error(error.message) });
  const archive = trpc.simulation.archiveReadiness.useMutation({ onError: (error) => toast.error(error.message) });
  const runExchange = (event: FormEvent) => { event.preventDefault(); exchange.mutate({ foreignAmount, rate, quoteUnit }); };
  const runClosing = (event: FormEvent) => { event.preventDefault(); closing.mutate({ systemBalance, physicalBalance }); };
  const runRateShock = (event: FormEvent) => { event.preventDefault(); rateShock.mutate({ referenceRate, proposedRate, reviewThresholdPercent }); };
  const runArchive = (event: FormEvent) => { event.preventDefault(); archive.mutate({ closingChecklistComplete, stockOpnameReconciled }); };

  return <div className="mx-auto max-w-7xl space-y-6"><section><p className="flex items-center gap-2 text-xs font-bold tracking-[.16em] text-amber-700 uppercase"><ShieldCheck className="size-4" /> Ruang latihan</p><h1 className="mt-2 font-display text-3xl font-semibold text-[#18395f]">Simulasi aman tanpa data produksi.</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#475569]">Latih perhitungan bon, pemeriksaan perubahan kurs, rekonsiliasi kas, dan kelayakan arsip. Semua hasil dibuang setelah sesi ini dan tidak membuat nasabah, bon, saldo kas, stock opname, laporan, atau arsip resmi.</p></section><Badge className="status-pending">SIMULASI — TIDAK MASUK LAPORAN</Badge><div className="grid gap-6 xl:grid-cols-2">
    <Card className="border-[#dce6f0]"><CardHeader><Calculator className="size-5 text-[#3f9276]" /><CardTitle className="font-display mt-3 text-xl text-[#18395f]">Latihan hitung bon</CardTitle><CardDescription>Masukkan nominal, kurs, dan unit kuotasi untuk melihat nilai Rupiah yang akan dihitung.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={runExchange}><div className="grid gap-3 sm:grid-cols-3"><Field label="Nominal valuta" value={foreignAmount} setValue={setForeignAmount} /><Field label="Kurs" value={rate} setValue={setRate} /><Field label="Unit kuotasi" value={quoteUnit} setValue={setQuoteUnit} /></div><Button type="submit" disabled={exchange.isPending} className="w-full bg-[#183f70] text-white hover:bg-[#12345d]">{exchange.isPending ? "Menghitung…" : "Hitung latihan"}</Button></form>{exchange.data ? <Result title="Hasil latihan bon" main={formatIdrDecimal(exchange.data.rupiahAmount)} rows={[["Nominal valuta", exchange.data.foreignAmount], ["Kurs", exchange.data.rate], ["Unit kuotasi", exchange.data.quoteUnit], ["Nilai Rupiah", formatIdrDecimal(exchange.data.rupiahAmount)]]} /> : null}</CardContent></Card>
    <Card className="border-[#dce6f0]"><CardHeader><Calculator className="size-5 text-[#3f9276]" /><CardTitle className="font-display mt-3 text-xl text-[#18395f]">Latihan penutupan kas</CardTitle><CardDescription>Bandingkan saldo sistem dan hitung fisik tanpa membuat stock opname resmi.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={runClosing}><div className="grid gap-3 sm:grid-cols-2"><Field label="Saldo sistem" value={systemBalance} setValue={setSystemBalance} /><Field label="Hitung fisik" value={physicalBalance} setValue={setPhysicalBalance} /></div><Button type="submit" disabled={closing.isPending} className="w-full bg-[#183f70] text-white hover:bg-[#12345d]">{closing.isPending ? "Menghitung…" : "Bandingkan latihan"}</Button></form>{closing.data ? <Result title="Status latihan kas" main={closing.data.reconciliationStatus} rows={[["Saldo sistem", closing.data.systemBalance], ["Saldo fisik", closing.data.physicalBalance], ["Varians", closing.data.variance], ["Status", closing.data.reconciliationStatus]]} /> : null}</CardContent></Card>
    <Card className="border-[#dce6f0]"><CardHeader><ShieldAlert className="size-5 text-[#b8751e]" /><CardTitle className="font-display mt-3 text-xl text-[#18395f]">Latihan guncangan kurs</CardTitle><CardDescription>Uji apakah selisih kurs usulan melampaui ambang review. Hasilnya tidak mengajukan atau mengaktifkan kurs.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={runRateShock}><div className="grid gap-3 sm:grid-cols-3"><Field label="Kurs referensi" value={referenceRate} setValue={setReferenceRate} /><Field label="Kurs usulan" value={proposedRate} setValue={setProposedRate} /><Field label="Ambang review (%)" value={reviewThresholdPercent} setValue={setReviewThresholdPercent} /></div><Button type="submit" disabled={rateShock.isPending} className="w-full bg-[#183f70] text-white hover:bg-[#12345d]">{rateShock.isPending ? "Memeriksa…" : "Uji perubahan kurs"}</Button></form>{rateShock.data ? <Result title="Hasil latihan kurs" main={rateShock.data.reviewRequired ? "PERLU REVIEW MANUSIA" : "DALAM AMBANG"} rows={[["Kurs referensi", rateShock.data.referenceRate], ["Kurs usulan", rateShock.data.proposedRate], ["Selisih", `${Number(rateShock.data.differencePercent) > 0 ? "+" : ""}${rateShock.data.differencePercent}%`], ["Ambang review", `${rateShock.data.reviewThresholdPercent}%`]]} /> : null}</CardContent></Card>
    <Card className="border-[#dce6f0]"><CardHeader><FileText className="size-5 text-[#3f9276]" /><CardTitle className="font-display mt-3 text-xl text-[#18395f]">Latihan kelayakan arsip</CardTitle><CardDescription>Periksa urutan kontrol sebelum mencoba mencetak arsip penutupan latihan.</CardDescription></CardHeader><CardContent><form className="space-y-4" onSubmit={runArchive}><label className="flex items-start gap-3 rounded-xl border border-[#e0e8f1] bg-white p-3"><input type="checkbox" className="mt-0.5 size-4 accent-[#3e9365]" checked={closingChecklistComplete} onChange={(event) => setClosingChecklistComplete(event.target.checked)} /><span><span className="block text-sm font-semibold text-[#294665]">Checklist penutupan latihan selesai</span><span className="mt-1 block text-xs leading-5 text-[#6b7d92]">Mensimulasikan langkah serah-terima dan brankas telah diperiksa.</span></span></label><label className="flex items-start gap-3 rounded-xl border border-[#e0e8f1] bg-white p-3"><input type="checkbox" className="mt-0.5 size-4 accent-[#3e9365]" checked={stockOpnameReconciled} onChange={(event) => setStockOpnameReconciled(event.target.checked)} /><span><span className="block text-sm font-semibold text-[#294665]">Stock opname latihan direkonsiliasi</span><span className="mt-1 block text-xs leading-5 text-[#6b7d92]">Mensimulasikan hasil hitung fisik sudah diperiksa petugas berwenang.</span></span></label><Button type="submit" disabled={archive.isPending} className="w-full bg-[#183f70] text-white hover:bg-[#12345d]">{archive.isPending ? "Memeriksa…" : "Uji kelayakan arsip"}</Button></form>{archive.data ? <Result title="Status arsip latihan" main={archive.data.readyToArchive ? "SIAP CETAK LATIHAN" : "BELUM SIAP"} rows={[["Checklist penutupan", archive.data.closingChecklistComplete ? "Lengkap" : "Belum lengkap"], ["Stock opname", archive.data.stockOpnameReconciled ? "Direkonsiliasi" : "Belum direkonsiliasi"], ["Tindakan", archive.data.missing.length ? archive.data.missing.join(", ") : "Tidak ada langkah tersisa"]]} /> : null}</CardContent></Card>
  </div></div>;
}
