/**
 * goAML report_indicator_type — the full enum extracted verbatim from goAMLSchema.xsd (197 codes),
 * used for the report_indicators section of an LTKM (suspicious transaction) submission. This is
 * a completely different codebook from this app's internal TKM checklist
 * (shared/suspiciousTransactionIndicators.ts) — there is no reliable automatic mapping between
 * the two, so a compliance reviewer picks the applicable code(s) here manually at export time,
 * confirmed with the user rather than guessed.
 */
export type GoAmlReportIndicator = { code: string; label: string };

export const GOAML_REPORT_INDICATORS: GoAmlReportIndicator[] = [
  { code: "AUDIT-001", label: "Hasil Audit Kepatuhan dan Audit Khusus PPATK" },
  { code: "AUDIT-002", label: "Hasil Audit Kepatuhan LPP" },
  { code: "BATAL-001", label: "Pengguna jasa telah ditetapkan sebagai tersangka/terdakwa kasus tindak pidana." },
  { code: "BATAL-002", label: "Pengguna jasa terlibat dalam aktivitas ilegal dan/atau tindak kriminal" },
  { code: "BATAL-003", label: "Pengguna Jasa mengubah atau membatalkan transaksi setelah Penyedia Jasa meminta dokumen identitas" },
  { code: "BATAL-004", label: "Transaksi terkait high risk country TPPU/TPPT" },
  { code: "BATAL-005", label: "Transaksi melibatkan perusahaan fiktif/paper company" },
  { code: "CBCCCargo", label: "LPUTLB melalui cargo" },
  { code: "CBCCM-001", label: "Besarnya jumlah Uang Tunai dan/atau nilai Instrumen Pembayaran Lain yang dibawa" },
  { code: "CBCCM-002", label: "Dilakukan secara berulang dalam periode tertentu" },
  { code: "CBCCM-003", label: "Informasi dari PPATK dan/atau penegak hukum lainnya mengenai adanya Pembawaan Uang Tunai dan/atau Instrumen Pembayaran Lain yang diduga terkait dengan tindak pidana" },
  { code: "CBCCM-004", label: "Profil dan Perilaku Pembawa" },
  { code: "CBCCM-005", label: "Uang Tunai dan/atau Instrumen Pembayaran Lain yang dibawa tidak diberitahukan atau disembunyikan" },
  { code: "CBCCM-006", label: "Indikator Lainnya" },
  { code: "CBCCP-001", label: "Tidak memberitahukan Pembawaan Uang Tunai dan/atau Instrumen Pembayaran Lain" },
  { code: "CBCCP-002", label: "Telah memberitahukan Pembawaan Uang Tunai dan/atau Instrumen Pembayaran Lain, tetapi jumlah uang tunai dan/ atau Instrumen Pembayaran Lain yang dibawa lebih besar" },
  { code: "CBCCP-003", label: "Tidak memiliki persetujuan atas pembawaan uang tunai berupa Uang Kertas Asing" },
  { code: "CBCCP-004", label: "Telah memiliki persetujuan atas pembawaan uang tunai berupa Uang Kertas Asing, tetapi jumlah Uang Kertas Asing yang dibawa lebih besar dari jumlah yang diberikan persetujuan" },
  { code: "CBCCP-005", label: "Tidak dilengkapi dengan izin dari Bank Indonesia bagi pembawaan mata uang Rupiah paling sedikit Rp 100.000.000,00 (seratus juta Rupiah) ke luar Daerah Pabean Indonesia" },
  { code: "CBCCPOS", label: "LPUTLB melalui Pos" },
  { code: "CSE-001", label: "Child Sex Exploitation" },
  { code: "HENTI-001", label: "Penghentian sementara berdasarkan permintaan PPATK" },
  { code: "HINDAR-001", label: "Transaksi bernilai kecil namun dengan frekuensi tinggi (structuring)" },
  { code: "HINDAR-002", label: "Transaksi menggunakan beberapa rekening atas nama individu yang berbeda-beda untuk kepentingan satu orang tertentu (smurfing)" },
  { code: "HINDAR-003", label: "Pengguna Jasa/kuasanya mencoba mempengaruhi petugas untuk tidak melaporkan TKM" },
  { code: "HINDAR-004", label: "Transaksi di berbagai daerah untuk menghindari deteksi" },
  { code: "HINDAR-005", label: "Transaksi sebagai pihak ketiga" },
  { code: "HINDAR-006", label: "Keingintahuan berlebih tentang sistem internal, dan pengawasan yang berlaku" },
  { code: "HINDAR-007", label: "Data pengguna jasa tidak konsisten saat identifikasi/verifikasi dan tidak dapat dijelaskan" },
  { code: "HINDAR-008", label: "Pembukaan rekening mirip dengan nama orang/entitas bisnis yang dikenal publik" },
  { code: "HINDAR-009", label: "Penghindaran threshold transaksi tunai per hari dalam beberapa hari berturut-turut" },
  { code: "HINDAR-010", label: "Transaksi pada hari dan cabang yang sama tetapi melalui petugas teller yang berbeda-beda" },
  { code: "HINDAR-011", label: "Penolakan/menyamarkan dari pengungkapan pemilik manfaat (beneficiary ownership)" },
  { code: "INDIW-001", label: "Initial Watchlist terduga TPPU" },
  { code: "INDTPA-001", label: "Korupsi" },
  { code: "INDTPA-002", label: "Penyuapan" },
  { code: "INDTPA-003", label: "Narkotika" },
  { code: "INDTPA-004", label: "Psikotropika" },
  { code: "INDTPA-005", label: "Penyelundupan Tenaga Kerja" },
  { code: "INDTPA-006", label: "Penyelundupan Migran" },
  { code: "INDTPA-007", label: "Di Bidang Perbankan" },
  { code: "INDTPA-008", label: "Di Bidang Pasar Modal" },
  { code: "INDTPA-009", label: "Di Bidang Perasuransian" },
  { code: "INDTPA-010", label: "Kepabeanan" },
  { code: "INDTPA-011", label: "Cukai" },
  { code: "INDTPA-012", label: "Perdagangan Orang" },
  { code: "INDTPA-013", label: "Perdagangan Senjata Gelap" },
  { code: "INDTPA-014", label: "Terorisme" },
  { code: "INDTPA-015", label: "Penculikan" },
  { code: "INDTPA-016", label: "Pencurian" },
  { code: "INDTPA-017", label: "Penggelapan" },
  { code: "INDTPA-018", label: "Penipuan" },
  { code: "INDTPA-019", label: "Pemalsuan Uang" },
  { code: "INDTPA-020", label: "Perjudian" },
  { code: "INDTPA-021", label: "Prostitusi" },
  { code: "INDTPA-022", label: "Di Bidang Perpajakan" },
  { code: "INDTPA-023", label: "Di Bidang Kehutanan" },
  { code: "INDTPA-024", label: "Di Bidang Lingkungan Hidup" },
  { code: "INDTPA-025", label: "Di Bidang Kelautan dan Perikanan" },
  { code: "INDTPA-026", label: "Indikasi Tindak pidana lain yang diancam pidana 4 tahun" },
  { code: "INQUIRY-001", label: "Pemenuhan bantuan hukum timbal balik dalam masalah pidana" },
  { code: "INQUIRY-002", label: "Penelusuran aset, dalam rangka pemulihan aset" },
  { code: "INQUIRY-003", label: "Pemeriksaan Laporan Harta Kekayaan Penyelenggara Negara (LHKPN)" },
  { code: "INQUIRY-004", label: "Optimalisasi penerimaan negara" },
  { code: "INQUIRY-005", label: "Audit LPP/Joint Audit PPATK" },
  { code: "INQUIRY-006", label: "Seleksi pengangkatan pejabat strategis" },
  { code: "INQUIRY-007", label: "Penanganan tindak pidana" },
  { code: "INQUIRY-008", label: "Audit investigasi (Itjen, BPK, BPKP, audit internal dsb)" },
  { code: "INQUIRY-009", label: "Membahayakan keamanan nasional" },
  { code: "INQUIRY-010", label: "Organisasi/lembaga internasional" },
  { code: "KOREKSI-001", label: "Koreksi atas laporan yang sudah pernah disampaikan ke PPATK secara proaktif oleh Pihak Pelapor atau berdasarkan hasil temuan PPATK yang disampaikan ke Pihak Pelapor melalui Message board. Bukan koreksi akibat penolakan oleh skema XML atau business rules" },
  { code: "LT-001", label: "Transaksi senilai => Rp500 juta dengan pembelian tunai bertahap" },
  { code: "LT-002", label: "Transaksi senilai => Rp 500 juta dengan menggunakan uang tunai, cek atau giro maupun pentransferan, pemindahbukuan atau metode pembayaran lainnya" },
  { code: "LT-003", label: "Transaksi senilai => Rp 500 juta atas nama Pihak Lain yang telah dilaporkan sebelumnya" },
  { code: "LT-004", label: "Transaksi hibah senilai Rp 500 juta" },
  { code: "MBG-001", label: "Program Makan Bergizi Gratis" },
  { code: "MINTA-001", label: "Pengguna Jasa telah ditetapkan sebagai tersangka/terdakwa dalam kasus tindak pidana." },
  { code: "MINTA-002", label: "Transaksi keuangan terkait proses analisis maupun pemeriksaan PPATK" },
  { code: "MINTA-003", label: "Transaksi keuangan terkait proses penyelidikan atau penyidikan yang dilakukan aparat penegak hukum" },
  { code: "MINTA-004", label: "Transaksi mellibatkan pihak yang terdaftar dalam Sanction List" },
  { code: "MINTA-005", label: "Transaksi Pengguna Jasa dalam Daftar Hitam Nasional/DPO atau Office of Foreign Asset Control (OFAC List)" },
  { code: "MINTA-006", label: "Permintaan informasi PPATK yang ditindaklanjuti dengan penyampaian LTKM proaktif" },
  { code: "MINTA-007", label: "Pemeriksaan PPATK yang ditindaklanjuti dengan penyampaian LTKM proaktif" },
  { code: "PEMILU-A", label: "(PEMILU-A) Formulir Pembukaan RKDK" },
  { code: "PEMILU-B", label: "(PEMILU-B) Mutasi Transaksi RKDK di Wilayah Berisiko Tinggi" },
  { code: "PEMILU-C", label: "(PEMILU-C) Mutasi Transaksi Rekening Bendahara Parpol, Dewan Pimpinan Partai Politik tingkat Pusat (DPP), Dewan Pimpinan Partai Politik tingkat Provinsi, Dewan Pimpinan Partai Politik tingkat Kabupaten/Kota" },
  { code: "PEMILU-D", label: "(PEMILU-D) Total mutasi debet dan kredit Kepala Daerah dan Legislatif pemenang periode Pemilu sebelumnya" },
  { code: "PEMILU-E", label: "(PEMILU-E) Transaksi Redflags Indikasi Terkait Pemilu" },
  { code: "PEMILU-F", label: "(PEMILU-F) Transaksi Kripto Top 10 Dari Luar Negeri" },
  { code: "POLA-001", label: "Transaksi PEPs" },
  { code: "POLA-002", label: "Sumber dana tidak dapat jelaskan" },
  { code: "POLA-003", label: "Transaksi tidak sesuai Profil" },
  { code: "POLA-004", label: "Transaksi tunai dalam jumlah di luar kebiasaan" },
  { code: "POLA-005", label: "Transaksi valuta asing dalam jumlah besar" },
  { code: "POLA-006", label: "Dana masuk dalam jumlah besar ke rekening dormant" },
  { code: "POLA-007", label: "Dana masuk dengan frekuensi tinggi dari pihak yang tidak memiliki hubungan jelas" },
  { code: "POLA-008", label: "Nominee (transaksi untuk kepentingan pihak lain)" },
  { code: "POLA-009", label: "Pelunasan dipercepat atas kredit atau pembiayaan dalam jumlah besar" },
  { code: "POLA-010", label: "Uang muka hampir senilai objek pembiayaan" },
  { code: "POLA-011", label: "Pembayaran angsuran/uang muka oleh pihak lain yang tidak memiliki hubungan jelas" },
  { code: "POLA-012", label: "Pembayaran uang muka secara tunai dalam jumlah besar yang tidak sesuai dengan profil" },
  { code: "POLA-013", label: "Pembayaran biaya premi dari rekening pihak lain yang tidak tercantum dalam penanggung atau tertanggung polis" },
  { code: "POLA-014", label: "Pembukaan beberapa polis asuransi dalam waktu berdekatan" },
  { code: "POLA-015", label: "Pembayaran premi melebihi batasan" },
  { code: "POLA-016", label: "Pembatalan polis asuransi dalam waktu yang berdekatan dengan waktu pembukaan polis" },
  { code: "POLA-017", label: "Pembayaran premi dilakukan sebelum dilakukan pembukaan polis asuransi" },
  { code: "POLA-018", label: "Pengembalian (refund) dana pembayaran premi asurasi atas polis asuransi yang belum terbit" },
  { code: "POLA-019", label: "Pencairan premi atau klaim ditransfer ke rekening milik pihak lain yang tidak tercantum dalam polis" },
  { code: "POLA-020", label: "Pencairan dini (early termination) atas produk polis asuransi" },
  { code: "POLA-021", label: "Redemption unit penyertaan yang baru dibeli tanpa memperhatikan kerugian atau tanpa underlying yang jelas" },
  { code: "POLA-022", label: "Pencairan premi di masa percobaan (free look period)." },
  { code: "POLA-023", label: "Transaksi efek secara tunai, transfer, atau cek atas nama orang lain tanpa sepengetahuan perusahaan efek" },
  { code: "POLA-024", label: "Transaksi atas saham yang berkapitalisasi kecil atau tidak likuid" },
  { code: "POLA-025", label: "Dana masuk ke Rekening Dana Investor dari pihak lain yang tidak jelas" },
  { code: "POLA-026", label: "Perpindahan saham dari pihak yang tidak jelas" },
  { code: "POLA-027", label: "Transaksi di pasar negosiasi pada saham yang tidak umum (terindikasi Unusual Market Activity)" },
  { code: "POLA-028", label: "Pembayaran transaksi tutup sendiri (crossing) langsung antara buyer dan seller" },
  { code: "POLA-029", label: "Penggunaan dokumen palsu atau diragukan kebenarannya" },
  { code: "POLA-030", label: "Dana tunai disimpan pada rekening dana investor yang dikelola oleh perusahaan efek dalam waktu relatif lama tanpa melakukan transaksi" },
  { code: "POLA-031", label: "Transaksi atas saham yang tidak aktif dengan tidak memperhatikan keuntungan/ kerugiannya" },
  { code: "POLA-032", label: "Transaksi efek dari atau ke beberapa sekuritas dalam waktu yang simultan atau berdekatan" },
  { code: "POLA-033", label: "Rekening efek pasif namun sering digunakan untuk melakukan pengiriman dana" },
  { code: "POLA-034", label: "Penyetoran dana jauh lebih besar dari pembayaran nilai transaksinya" },
  { code: "POLA-035", label: "Permintaan pembayaran transaksi valas ditransfer ke rekening bank" },
  { code: "POLA-036", label: "Permintaan pembayaran hasil penjualan valas dengan menggunakan cek" },
  { code: "POLA-037", label: "Transaksi deposit payment dalam jumlah besar menggunakan Alat Pembayaran Menggunakan Kartu" },
  { code: "POLA-038", label: "Penyetoran (pelunasan tagihan) selalu dilakukan oleh pihak lain" },
  { code: "POLA-039", label: "Pembayaran iuran koperasi oleh pihak lain" },
  { code: "POLA-040", label: "Pembayaran pinjaman pada koperasi oleh pihak lain" },
  { code: "POLA-041", label: "Pencairan dana iuran koperasi dikirimkan ke pihak lain" },
  { code: "POLA-042", label: "Pelunasan pinjaman dipercepat sebelum jatuh tempo" },
  { code: "POLA-043", label: "Percepatan pelunasan barang gadai dengan uang dalam jumlah besar" },
  { code: "POLA-044", label: "Pengguna Jasa tidak khawatir akan penyitaan barang gadainya" },
  { code: "POLA-045", label: "Pelunasan barang gadai dilakukan oleh pihak lain yang tidak memiliki hubungan dengan pengguna jasa" },
  { code: "POLA-046", label: "Penyetoran dana oleh pihak lain" },
  { code: "POLA-047", label: "Penyetoran ke rekening segregate account pialang komoditi dipecah melalui beberapa bank" },
  { code: "POLA-048", label: "Tidak terdapat hubungan yang jelas antara Pengguna Jasa dengan pemegang Bukti Kepemilikan Kendaraan Bermotor" },
  { code: "POLA-049", label: "Pembawaaun Uang tunai/instrumen pembayaran lain senilai => Rp 1 miliar atau setara dilakukan oleh pihak yang tidak memiliki ijin dari otoritas" },
  { code: "POLA-050", label: "Pembawaan uang tunai berulang dalam 1 (satu) hari" },
  { code: "POLA-051", label: "Pembawaan uang tunai berulang yang terpola dalam periode tertentu" },
  { code: "POLA-052", label: "Profil dan perilaku pembawa uang tunai memiliki hubungan dengan negara atau yuridiksi berisiko tinggi" },
  { code: "POLA-053", label: "Profil dan perilaku pembawa uang tunai memiliki hubungan dengan pembawaan barang impor/ekspor yang tidak wajar, yang berisiko tinggi atau yang pernah ditegah sebelumnya" },
  { code: "POLA-054", label: "Profil dan perilaku pembawaan uang tunai memilki riwayat catatan kriminal, riwayat kehilangan dokumen perjalanan yang tidak wajar" },
  { code: "POLA-055", label: "Pembawaan uang tunai yang ditempatkan secara tidak wajar atau tidak diberitahukan" },
  { code: "POLA-056", label: "Pengoperasian dan pengelolaan perusahaan klien" },
  { code: "POLA-057", label: "Pendirian, pembelian dan penjualan badan hukum klien" },
  { code: "POLA-058", label: "Pembelian dan penjualan properti" },
  { code: "POLA-059", label: "Pengelolaan terhadap uang, efek, dan/atau produk jasa keuangan lainnya" },
  { code: "POLA-060", label: "Pengelolaan rekening giro, rekening tabungan, rekening deposito, dan/atau rekening efek" },
  { code: "PPP", label: "Terkait Public Private Partnership (PPP)" },
  { code: "PPP-BEC", label: "Public-Private Partnership TP Business Email Compromise" },
  { code: "PPP-KOPERASI", label: "Terkait Investment Fraud Sektor Koperasi" },
  { code: "PPP-NARKOTIKA", label: "Public-Private Partnership TP Narkotika" },
  { code: "PPP-TAMBANG", label: "Terkait GFC Sektor Pertambangan" },
  { code: "PUTUS-001", label: "Informasi yang tidak benar terkait identitas, sumber penghasilan atau usahanya" },
  { code: "PUTUS-002", label: "Penggunaan dokumen identitas palsu atau diragukan kebenarannya" },
  { code: "PUTUS-003", label: "Enggan atau menolak memberikan informasi/dokumen yang diminta" },
  { code: "PUTUS-004", label: "Tidak bersedia memberikan informasi yang benar atau segera memutuskan hubungan usaha pada saat petugas meminta informasi atas transaksi yang dilakukannya" },
  { code: "PUTUS-005", label: "Enggan memberikan informasi sumber dana dan tujuan transaksi secara lengkap" },
  { code: "PUTUS-006", label: "Transaksi menggunakan nama yang berbeda (ejaan yang berbeda) dari satu transaksi ke transaksi yang lain" },
  { code: "PUTUS-007", label: "Transaksi melibatkan perusahaan fiktif dengan indikasi menggunakan dokumen palsu" },
  { code: "PUTUS-008", label: "Mempengaruhi petugas untuk tidak melengkapi dokumen yang diperlukan untuk melakukan transaksi" },
  { code: "PUTUS-009", label: "Informasi diragukan/tidak jelas" },
  { code: "PUTUS-010", label: "Menolak memberikan dokumen identitas pribadi" },
  { code: "PUTUS-011", label: "Identitas yang diberikan tidak dapat diperiksa kebenarannya" },
  { code: "PUTUS-012", label: "Menggunakan dokumen identitas yang berbeda-beda setiap kali melakukan transaksi" },
  { code: "TBMLDOC-001", label: "KYC Mencurigakan" },
  { code: "TBMLDOC-002", label: "L/C Mencurigakan" },
  { code: "TBMLDOC-003", label: "Faktur Mencurigakan" },
  { code: "TBMLDOC-004", label: "Bill of exchange mencurigakan" },
  { code: "TBMLDOC-005", label: "Surat keterangan asal" },
  { code: "TBMLDOC-006", label: "Dokumen transportasi" },
  { code: "TBMLDOC-007", label: "Pola transaksi perdagangan" },
  { code: "TBMLINTT-01", label: "Proliferasi Nuklir" },
  { code: "TBMLINTT-02", label: "Daftar Sanksi" },
  { code: "TBMLTECH-01", label: "Over Invoicing" },
  { code: "TBMLTECH-02", label: "Under Invoicing" },
  { code: "TBMLTECH-03", label: "Split Invoicing" },
  { code: "TBMLTECH-04", label: "Overshipment" },
  { code: "TBMLTECH-05", label: "Undershipment" },
  { code: "TBMLTECH-06", label: "Mis-description of goods" },
  { code: "TBMLTECH-07", label: "Phantom Shipment" },
  { code: "TBMLTECH-08", label: "BMPE" },
  { code: "TBMLTECH-09", label: "Surrogate Shopping/Surrogate Buyer" },
  { code: "TBMLTECH-10", label: "Third party invoice settlement" },
  { code: "TBMLTECH-11", label: "Shell companies" },
  { code: "TEROR-001", label: "Transaksi melibatkan para pihak dalam Daftar Terduga Terorisme dan Organisasi Terorisme (DTTOT)" },
  { code: "TEROR-002", label: "Transaksi dilakukan oleh Bendahara/karyawan NPO menarik uang dari rekening NPO dan memasukannya ke rekening pribadi yang bersangkutan, kemudian mengirimkan sebagian dananya ke rekening tersangka teroris" },
  { code: "TEROR-003", label: "Dilaporkan dalam berita/media karena terkait dengan organisasi teroris" },
  { code: "TEROR-004", label: "Transaksi NPO (misalnya: pemilik rekening, pengirim, penerima atau pemilik manfaat) berasal dari negara yang dikenal sebagai negara yang mendukung kegiatan teroris atau organisasi teroris" },
  { code: "TEROR-005", label: "Aliran dana dari kantor utama NPO asing yang berada di negara berisiko tinggi terorisme, kepada cabang NPO asing yang berada di Indonesia" },
  { code: "TEROR-006", label: "Instruksi transaksi yang tidak wajar dan mengandung kata/istilah yang berkaitan dengan ekstrimisme dan ideologi teroris serta indikasi tindak pidana lain" },
  { code: "TEROR-007", label: "Tidak dapat menjelaskan dan/atau minim dokumen pendukung ketika pihak bank menanyakan alasan/tujuan NPO mentransferkan dananya ke wilayah atau kepada pihak berisiko tinggi terorisme" },
  { code: "TEROR-008", label: "Rekening NPO untuk menampung dana milik terduga teroris dan asosiasinya" },
  { code: "TEROR-009", label: "Transaksi yang melibatkan pihak yang terindikasi proliferasi" },
  { code: "TUNDA-001", label: "Penundaan transaksi yang dilakukan atas inisiatif PJK" },
  { code: "TUNDA-002", label: "Penundaan transaksi berdasarkan perintah penyidik, penuntut umum, atau hakim" },
];

export const GOAML_REPORT_INDICATOR_CODES = new Set(GOAML_REPORT_INDICATORS.map((indicator) => indicator.code));

export function isKnownGoAmlReportIndicator(code: string) {
  return GOAML_REPORT_INDICATOR_CODES.has(code);
}
