/** ISO 4217 currency codes and names, for the currency search box in Buat Transaksi and Kas & Persediaan.
 * This is a static reference list only — picking one calls `currencies.ensure` to register it in the
 * `currencies` table on first use. It is independent of BI/JISDOR rate sync, which only ever covers a
 * handful of codes; a currency existing here (or in the database) never implies it has an active rate. */
export type WorldCurrency = { code: string; name: string };

export const WORLD_CURRENCIES: WorldCurrency[] = [
  { code: "IDR", name: "Rupiah Indonesia" },
  { code: "USD", name: "Dolar Amerika Serikat" },
  { code: "EUR", name: "Euro" },
  { code: "GBP", name: "Poundsterling Inggris" },
  { code: "JPY", name: "Yen Jepang" },
  { code: "AUD", name: "Dolar Australia" },
  { code: "CAD", name: "Dolar Kanada" },
  { code: "CHF", name: "Franc Swiss" },
  { code: "CNY", name: "Yuan Tiongkok" },
  { code: "HKD", name: "Dolar Hong Kong" },
  { code: "NZD", name: "Dolar Selandia Baru" },
  { code: "SGD", name: "Dolar Singapura" },
  { code: "MYR", name: "Ringgit Malaysia" },
  { code: "THB", name: "Baht Thailand" },
  { code: "PHP", name: "Peso Filipina" },
  { code: "VND", name: "Dong Vietnam" },
  { code: "KRW", name: "Won Korea Selatan" },
  { code: "TWD", name: "Dolar Taiwan Baru" },
  { code: "INR", name: "Rupee India" },
  { code: "PKR", name: "Rupee Pakistan" },
  { code: "BDT", name: "Taka Bangladesh" },
  { code: "LKR", name: "Rupee Sri Lanka" },
  { code: "NPR", name: "Rupee Nepal" },
  { code: "MMK", name: "Kyat Myanmar" },
  { code: "KHR", name: "Riel Kamboja" },
  { code: "LAK", name: "Kip Laos" },
  { code: "BND", name: "Dolar Brunei" },
  { code: "MOP", name: "Pataca Makau" },
  { code: "MNT", name: "Tugrik Mongolia" },
  { code: "AED", name: "Dirham Uni Emirat Arab" },
  { code: "SAR", name: "Riyal Arab Saudi" },
  { code: "QAR", name: "Riyal Qatar" },
  { code: "KWD", name: "Dinar Kuwait" },
  { code: "BHD", name: "Dinar Bahrain" },
  { code: "OMR", name: "Rial Oman" },
  { code: "JOD", name: "Dinar Yordania" },
  { code: "ILS", name: "Shekel Baru Israel" },
  { code: "LBP", name: "Pound Lebanon" },
  { code: "IQD", name: "Dinar Irak" },
  { code: "IRR", name: "Rial Iran" },
  { code: "YER", name: "Rial Yaman" },
  { code: "TRY", name: "Lira Turki" },
  { code: "EGP", name: "Pound Mesir" },
  { code: "ZAR", name: "Rand Afrika Selatan" },
  { code: "NGN", name: "Naira Nigeria" },
  { code: "KES", name: "Shilling Kenya" },
  { code: "GHS", name: "Cedi Ghana" },
  { code: "TZS", name: "Shilling Tanzania" },
  { code: "UGX", name: "Shilling Uganda" },
  { code: "ETB", name: "Birr Ethiopia" },
  { code: "MAD", name: "Dirham Maroko" },
  { code: "DZD", name: "Dinar Aljazair" },
  { code: "TND", name: "Dinar Tunisia" },
  { code: "XOF", name: "Franc CFA Afrika Barat" },
  { code: "XAF", name: "Franc CFA Afrika Tengah" },
  { code: "RUB", name: "Ruble Rusia" },
  { code: "UAH", name: "Hryvnia Ukraina" },
  { code: "PLN", name: "Zloty Polandia" },
  { code: "CZK", name: "Koruna Ceko" },
  { code: "HUF", name: "Forint Hungaria" },
  { code: "RON", name: "Leu Rumania" },
  { code: "BGN", name: "Lev Bulgaria" },
  { code: "HRK", name: "Kuna Kroasia" },
  { code: "RSD", name: "Dinar Serbia" },
  { code: "SEK", name: "Krona Swedia" },
  { code: "NOK", name: "Krone Norwegia" },
  { code: "DKK", name: "Krone Denmark" },
  { code: "ISK", name: "Krona Islandia" },
  { code: "GEL", name: "Lari Georgia" },
  { code: "AMD", name: "Dram Armenia" },
  { code: "AZN", name: "Manat Azerbaijan" },
  { code: "KZT", name: "Tenge Kazakhstan" },
  { code: "UZS", name: "Som Uzbekistan" },
  { code: "MXN", name: "Peso Meksiko" },
  { code: "BRL", name: "Real Brasil" },
  { code: "ARS", name: "Peso Argentina" },
  { code: "CLP", name: "Peso Chili" },
  { code: "COP", name: "Peso Kolombia" },
  { code: "PEN", name: "Sol Peru" },
  { code: "UYU", name: "Peso Uruguay" },
  { code: "BOB", name: "Boliviano Bolivia" },
  { code: "PYG", name: "Guarani Paraguay" },
  { code: "VES", name: "Bolivar Venezuela" },
  { code: "DOP", name: "Peso Republik Dominika" },
  { code: "JMD", name: "Dolar Jamaika" },
  { code: "TTD", name: "Dolar Trinidad dan Tobago" },
  { code: "BSD", name: "Dolar Bahama" },
  { code: "BBD", name: "Dolar Barbados" },
  { code: "XCD", name: "Dolar Karibia Timur" },
  { code: "PGK", name: "Kina Papua Nugini" },
  { code: "FJD", name: "Dolar Fiji" },
  { code: "WST", name: "Tala Samoa" },
  { code: "TOP", name: "Paʻanga Tonga" },
  { code: "SBD", name: "Dolar Kepulauan Solomon" },
  { code: "VUV", name: "Vatu Vanuatu" },
  { code: "XPF", name: "Franc CFP" },
  { code: "AFN", name: "Afghani Afghanistan" },
  { code: "ALL", name: "Lek Albania" },
  { code: "AOA", name: "Kwanza Angola" },
  { code: "BAM", name: "Marka Bosnia dan Herzegovina" },
  { code: "BIF", name: "Franc Burundi" },
  { code: "BMD", name: "Dolar Bermuda" },
  { code: "BTN", name: "Ngultrum Bhutan" },
  { code: "BWP", name: "Pula Botswana" },
  { code: "BYN", name: "Ruble Belarus" },
  { code: "BZD", name: "Dolar Belize" },
  { code: "CDF", name: "Franc Kongo" },
  { code: "CRC", name: "Colon Kosta Rika" },
  { code: "CUP", name: "Peso Kuba" },
  { code: "CVE", name: "Escudo Tanjung Verde" },
  { code: "DJF", name: "Franc Djibouti" },
  { code: "ERN", name: "Nakfa Eritrea" },
  { code: "FKP", name: "Pound Kepulauan Falkland" },
  { code: "GIP", name: "Pound Gibraltar" },
  { code: "GMD", name: "Dalasi Gambia" },
  { code: "GNF", name: "Franc Guinea" },
  { code: "GTQ", name: "Quetzal Guatemala" },
  { code: "GYD", name: "Dolar Guyana" },
  { code: "HNL", name: "Lempira Honduras" },
  { code: "HTG", name: "Gourde Haiti" },
  { code: "KGS", name: "Som Kirgizstan" },
  { code: "KYD", name: "Dolar Kepulauan Cayman" },
  { code: "LRD", name: "Dolar Liberia" },
  { code: "LSL", name: "Loti Lesotho" },
  { code: "LYD", name: "Dinar Libya" },
  { code: "MDL", name: "Leu Moldova" },
  { code: "MGA", name: "Ariary Madagaskar" },
  { code: "MKD", name: "Denar Makedonia Utara" },
  { code: "MRU", name: "Ouguiya Mauritania" },
  { code: "MUR", name: "Rupee Mauritius" },
  { code: "MVR", name: "Rufiyaa Maladewa" },
  { code: "MWK", name: "Kwacha Malawi" },
  { code: "MZN", name: "Metical Mozambik" },
  { code: "NAD", name: "Dolar Namibia" },
  { code: "NIO", name: "Cordoba Nikaragua" },
  { code: "PAB", name: "Balboa Panama" },
  { code: "RWF", name: "Franc Rwanda" },
  { code: "SCR", name: "Rupee Seychelles" },
  { code: "SDG", name: "Pound Sudan" },
  { code: "SLL", name: "Leone Sierra Leone" },
  { code: "SOS", name: "Shilling Somalia" },
  { code: "SRD", name: "Dolar Suriname" },
  { code: "SSP", name: "Pound Sudan Selatan" },
  { code: "STN", name: "Dobra Sao Tome dan Principe" },
  { code: "SYP", name: "Pound Suriah" },
  { code: "SZL", name: "Lilangeni Eswatini" },
  { code: "TJS", name: "Somoni Tajikistan" },
  { code: "TMT", name: "Manat Turkmenistan" },
  { code: "XDR", name: "Hak Penarikan Khusus IMF" },
  { code: "ZMW", name: "Kwacha Zambia" },
  { code: "ZWL", name: "Dolar Zimbabwe" },
].sort((a, b) => a.code.localeCompare(b.code));
